<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1 (Total recall) 

|Term|Brief Description|
|:---|:---:|
|Subsetting|Selecting a part of the data from an entire list or array.|
|Indexing|Giving an index to each element of the dataset, according to their respective positions in the list. _corrected answer: selecting one element_|
|Slicing|_selecting a range of elements_|
|Masking|Give a condition and make all 'True' events of that condition = 1, all 'False' events = 0. We can use the masking function to filter out values such that we only obtain either 'True' or 'False' events as output|

## Exercise 2 (Show me the ‘odd’ letters)

In [50]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2d[:10, 0] #subset all the first elements

int_array = np_array_2d[:10, 0].astype(int) #convert np_array_2d subset into integers using astype(int)

int_array % 2 #remainders for division by 2

my_mask = int_array % 2 == 1 #check for whether integer in the array was divisible by 2. 'True' event = remainder was 1; number is non-divisble by 2; odd number. 'False' event = even number

np_array_2d[my_mask]

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U11')

In [56]:
#to extract the corresponding second elements

odd_numbers = np_array_2d[my_mask]

odd_numbers[:10, 1]

print(f'These are the \'odd letters\': {odd_numbers[:10, 1]}.')

These are the 'odd letters': ['A' 'C' 'E' 'G' 'I'].


## Exercise 3  

In [77]:
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

# Apply conditions directly to the array using boolean indexing
array[array < 50] = -1 # Set -1 where values are less than 50
array[array > 50] = +1 # Set +1 where values are more than 50
array[array == 50] = 0 # Set 0 where values are equal to 50

print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
