<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

In [3]:
import numpy as np

In [4]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(py_list)

x = py_list
x = np_array

In [5]:
x[0] #first element

'a1'

In [6]:
x[-3] #third last element from the back

'h8'

In [10]:
x[::-1] #reverses the list

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

In [12]:
x[::-2] #reverse the list, and select by intervals of 2

array(['j10', 'h8', 'f6', 'd4', 'b2'], dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [13]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [14]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[np_array > 3] #alternative method to show the True subset, without creating another variable

array([ 4,  5,  6,  7,  8,  9, 10])

In [47]:
### example 1: Bitwise NOT operator

np_array[~(np_array > 3)]  #'~' is the Bitwise Not operator. this statement stands for np_array NOT larger than 3

array([1, 2, 3])

In [48]:
### example 2: Bitwise AND operator

np_array[(np_array > 3) & (np_array < 8)] # this is how we can combine one mask and another mask. '&' means 'AND'

array([4, 5, 6, 7])

In [49]:
### example 3: Bitwise OR operator

np_array[(np_array < 3) | (np_array > 8)] # combines the results of both masks, and gives the output for when either of them is true.

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [23]:
py_list_2d = [[1, "A"],[2, "B"],[3, "C"],[4, "D"],[5, "E"],[6, "F"],[7, "G"],[8, "H"],[9, "I"],[10, "J"]]

np_array_2d = np.array(py_list_2d)

In [50]:
### example 1.1

py_list_2d[3]

[4, 'D']

In [51]:
### example 1.2

np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [27]:
### example 2.1

py_list_2d[3][0] #first element at position 4/index 3

4

In [52]:
### example 2.2

np_array_2d[3,0]

'4'

In [53]:
### example 3.1

py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [54]:
### example 3.2

np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [55]:
### example 4.1

py_list_2d[:3][0] #special case. first elements of all sub-lists up to 2?

[1, 'A']

In [56]:
### example 4.2

np_array_2d[:3,0]

array(['1', '2', '3'], dtype='<U11')

In [57]:
### example 5.1

py_list_2d[3:6][0]

[4, 'D']

In [58]:
### example 5.2

np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [59]:
### example 5.3

np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

In [45]:
np_array[:] #to choose everything in the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 1.4 Growing lists

In [60]:
x = [1,2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [61]:
### example 1

x=[1]
x= x+[2]
x= x+[3]
x= x+[4]
x

[1, 2, 3, 4]

In [63]:
### example 2

x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [65]:
### example 3

x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [66]:
## difference between extend and append

x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [67]:
x.extend([4, 5, 6])
x

x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [68]:
a=(1, 2, 3) #define tuple

In [69]:
print(a[0]) #accessing data of a tuple

1


In [70]:
a[0] = -1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [74]:
x=[1, 2, 3]
y=x #WRONG way to copy a list
z=x

y

[1, 2, 3]

In [75]:
x=[1,2, 3]
y=x.copy()
z=x.copy()

z

[1, 2, 3]

## Footnotes