<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [12]:
import numpy as np

In [28]:
## Lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [25]:
## Arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [16]:
## Dictionary
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [32]:
py_super_names[0] #1st position, index 0

'Black Widow'

In [31]:
py_real_names[0]

'Natasha Romanoff'

In [33]:
py_super_names[-1]   # Reverse indexing. element in the last position

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [1]:
superhero_info = {"Natasha Romanoff":"Black Widow",
                 "Tony Stark":"Iron Man",
                 "Stephen Strange":"Doctor Strange"}

In [2]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [5]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [9]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

## 2.1 Size

In [13]:
py_list_2d = [[1,"A"], [2,"B"], [3,"C"], [4,"D"], [5,"E"], [6,"F"], [7,"G"], [8,"H"], [9,"I"], [10,"J"]]

np_array_2d = np.array(py_list_2d)

In [14]:
len(py_list_2d)
len(np_array_2d)
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [15]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [16]:
py_list

[1, 1.5, 'A']

In [17]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) #can reuse the python list to create a NEW numpy array

In [20]:
np_array + 10

array([11, 12, 13, 14, 15])

In [21]:
py_list + 10 #cannot reuse the list

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [24]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [26]:
py_list_1 + py_list_2 #adding lists causes the number of elements to grow

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [27]:
np_array_1 + np_array_2 #adding arrays is an element-wise operation. aka the sum of the first elements of each array

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

py_list*2 #number of elements grow, and the values within just repeats in the sequence according to the multiplier.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [35]:
np_array*2 #results in the product of 2 elements in their corresponding positions

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [38]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [39]:
py_list**2 #wont work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [45]:
py_list == 3 #works, but what is the question?
np_array == 3
np_array > 3

array([False, False, False,  True,  True])

In [47]:
py_list == 3

False

In [46]:
np_array == 3
np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [48]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [60]:
sum(py_list) # sum() is a base Python function

15

In [58]:
max(py_list) # max() is a base Python function

5

In [59]:
min(py_list) # min() is a base Python function

1

In [53]:
np_array.sum()

15

In [54]:
np_array.max()


5

In [55]:
np_array.min()

1

In [56]:
np_array.mean()

3.0

In [57]:
np_array.std()

1.4142135623730951

## Footnotes